version: '3'

services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./:/app
        environment:
            - PORT=8080
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=go-gin
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    postgres:
        image: 'postgres'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=go-gin
        ports:
            - '5435:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

